brokerClusterName=DefaultCluster
brokerName=broker-a
brokerId=0
namesrvAddr=local-rocketmq-namesrv:9876
listenPort=10911
brokerIP1=payment-rocketmq-broker
autoCreateTopicEnable=true
enableScheduleMessage=false
storePathRootDir=/home/rocketmq/store
storePathCommitLog=/home/rocketmq/store/commitlog
