package com.example.payments.platform.service.service;

import java.util.Set;

/** Operation permissions required by the backend's administrative API surface. */
public final class AdminOperationPermissionCatalog {
  private static final Set<String> ALL =
      Set.of(
          "audit:list",
          "auth:me",
          "auth:password:change",
          "channel:create",
          "channel:health:list",
          "channel:list",
          "channel:status",
          "channel:update",
          "config-release:approve",
          "config-release:create",
          "config-release:diff",
          "config-release:list",
          "config-release:publish",
          "config-release:rollback",
          "config-release:submit",
          "configuration:snapshot:list",
          "dashboard:overview",
          "merchant-product:bind",
          "merchant-product:detail",
          "merchant-product:list",
          "merchant-product:status",
          "merchant-product:update",
          "merchant:contact:list",
          "merchant:contact:update",
          "merchant:create",
          "merchant:credential:list",
          "merchant:credential:revoke",
          "merchant:credential:rotate",
          "merchant:detail",
          "merchant:list",
          "merchant:profile",
          "merchant:profile:update",
          "merchant:status",
          "merchant:update",
          "order:list",
          "order:statistics",
          "outbox:detail",
          "outbox:list",
          "outbox:redrive",
          "payment-event:detail",
          "payment-event:list",
          "payment-event:replay",
          "pricing-rule:create",
          "pricing-rule:delete",
          "pricing-rule:detail",
          "pricing-rule:list",
          "pricing-rule:status",
          "pricing-rule:update",
          "product-capability:create",
          "product-capability:list",
          "product-capability:status",
          "product-capability:update",
          "product:create",
          "product:detail",
          "product:list",
          "product:status",
          "product:update",
          "reconciliation:bill:import",
          "reconciliation:bill:detail",
          "reconciliation:bill:list",
          "reconciliation:bill:reconcile",
          "reconciliation:difference:list",
          "reconciliation:difference:resolve",
          "risk-policy:create",
          "risk-policy:list",
          "risk-policy:status",
          "routing-rule:create",
          "routing-rule:delete",
          "routing-rule:detail",
          "routing-rule:list",
          "routing-rule:status",
          "routing-rule:update",
          "system:access:list",
          "system:data-scope:role:list",
          "system:data-scope:role:update",
          "system:data-scope:user:list",
          "system:data-scope:user:update",
          "system:menu:create",
          "system:menu:delete",
          "system:menu:list",
          "system:menu:permission:create",
          "system:menu:permission:delete",
          "system:menu:permission:list",
          "system:menu:permission:update",
          "system:menu:resource-type:create",
          "system:menu:resource-type:list",
          "system:menu:status",
          "system:menu:update",
          "system:permission:list",
          "system:role:create",
          "system:role:list",
          "system:role:permission:list",
          "system:role:permission:update",
          "system:role:update",
          "system:user:create",
          "system:user:detail",
          "system:user:list",
          "system:user:password:reset",
          "system:user:role:update",
          "system:user:status",
          "system:user:update");

  private AdminOperationPermissionCatalog() {}

  public static Set<String> all() {
    return ALL;
  }
}
