package com.example.payments.trade.service.domain;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.UUID;

public record PaymentOrder(
    String orderId,
    String merchantId,
    String merchantOrderNo,
    String productCode,
    OrderType orderType,
    String paymentMethod,
    String country,
    String currency,
    BigDecimal amount,
    BigDecimal feeAmount,
    BigDecimal payerPayableAmount,
    BigDecimal netAmount,
    String feeBearer,
    OrderStatus status,
    String idempotencyKey,
    String merchantRequestSnapshot,
    String routeSnapshot,
    String pricingSnapshot,
    Instant expireAt,
    Instant createdAt,
    Instant paidAt,
    String paymentToken,
    String notifyUrl,
    String returnUrl,
    String customerReference,
    String payoutDestinationRef,
    String description,
    String callbackStatus,
    String callbackEventId,
    Integer callbackAttemptCount,
    Instant callbackLastNotifiedAt,
    String callbackLastError) {

  public static PaymentOrder create(
      String merchantId,
      String merchantOrderNo,
      String productCode,
      String paymentMethod,
      String country,
      String currency,
      BigDecimal amount,
      String idempotencyKey,
      Instant expireAt,
      String notifyUrl,
      String returnUrl,
      String customerReference,
      String payoutDestinationRef,
      String description) {
    return create(
        UUID.randomUUID().toString(),
        OrderType.PAYIN,
        merchantId,
        merchantOrderNo,
        productCode,
        paymentMethod,
        country,
        currency,
        amount,
        idempotencyKey,
        null,
        expireAt,
        notifyUrl,
        returnUrl,
        customerReference,
        payoutDestinationRef,
        description);
  }

  public static PaymentOrder create(
      String merchantId,
      String merchantOrderNo,
      String productCode,
      String paymentMethod,
      String country,
      String currency,
      BigDecimal amount,
      String idempotencyKey,
      String merchantRequestSnapshot,
      Instant expireAt,
      String notifyUrl,
      String returnUrl,
      String customerReference,
      String payoutDestinationRef,
      String description) {
    return create(
        UUID.randomUUID().toString(),
        OrderType.PAYIN,
        merchantId,
        merchantOrderNo,
        productCode,
        paymentMethod,
        country,
        currency,
        amount,
        idempotencyKey,
        merchantRequestSnapshot,
        expireAt,
        notifyUrl,
        returnUrl,
        customerReference,
        payoutDestinationRef,
        description);
  }

  public static PaymentOrder create(
      String orderId,
      OrderType orderType,
      String merchantId,
      String merchantOrderNo,
      String productCode,
      String paymentMethod,
      String country,
      String currency,
      BigDecimal amount,
      String idempotencyKey,
      String merchantRequestSnapshot,
      Instant expireAt,
      String notifyUrl,
      String returnUrl,
      String customerReference,
      String payoutDestinationRef,
      String description) {
    BigDecimal fee = amount.multiply(new BigDecimal("0.0200")).setScale(2);
    return new PaymentOrder(
        orderId,
        merchantId,
        merchantOrderNo,
        productCode,
        orderType,
        paymentMethod,
        country,
        currency,
        amount,
        fee,
        amount,
        amount.subtract(fee),
        "MERCHANT",
        OrderStatus.CREATED,
        idempotencyKey,
        merchantRequestSnapshot,
        "{\"route\":\"simulated-channel\",\"version\":1}",
        "{\"feeRate\":\"0.0200\",\"mode\":\"INCLUSIVE\",\"version\":1}",
        expireAt,
        Instant.now(),
        null,
        "simulated-token-" + UUID.randomUUID(),
        notifyUrl,
        returnUrl,
        customerReference,
        payoutDestinationRef,
        description,
        notifyUrl == null ? "NOT_CONFIGURED" : "READY",
        null,
        0,
        null,
        null);
  }

  public PaymentOrder withIdentity(String nextOrderId, OrderType nextOrderType) {
    return new PaymentOrder(
        nextOrderId,
        merchantId,
        merchantOrderNo,
        productCode,
        nextOrderType,
        paymentMethod,
        country,
        currency,
        amount,
        feeAmount,
        payerPayableAmount,
        netAmount,
        feeBearer,
        status,
        idempotencyKey,
        merchantRequestSnapshot,
        routeSnapshot,
        pricingSnapshot,
        expireAt,
        createdAt,
        paidAt,
        paymentToken,
        notifyUrl,
        returnUrl,
        customerReference,
        payoutDestinationRef,
        description,
        callbackStatus,
        callbackEventId,
        callbackAttemptCount,
        callbackLastNotifiedAt,
        callbackLastError);
  }

  public PaymentOrder withStatus(OrderStatus nextStatus, Instant paymentTime) {
    if (status.isTerminal() && status != nextStatus) {
      return this;
    }
    return new PaymentOrder(
        orderId,
        merchantId,
        merchantOrderNo,
        productCode,
        orderType,
        paymentMethod,
        country,
        currency,
        amount,
        feeAmount,
        payerPayableAmount,
        netAmount,
        feeBearer,
        nextStatus,
        idempotencyKey,
        merchantRequestSnapshot,
        routeSnapshot,
        pricingSnapshot,
        expireAt,
        createdAt,
        nextStatus == OrderStatus.SUCCESS ? paymentTime : paidAt,
        paymentToken,
        notifyUrl,
        returnUrl,
        customerReference,
        payoutDestinationRef,
        description,
        callbackStatus,
        callbackEventId,
        callbackAttemptCount,
        callbackLastNotifiedAt,
        callbackLastError);
  }

  public PaymentOrder withPricing(
      BigDecimal fee,
      BigDecimal payerPayable,
      BigDecimal net,
      String feeBearer,
      String routeSnapshot,
      String pricingSnapshot) {
    return new PaymentOrder(
        orderId,
        merchantId,
        merchantOrderNo,
        productCode,
        orderType,
        paymentMethod,
        country,
        currency,
        amount,
        fee,
        payerPayable,
        net,
        feeBearer,
        status,
        idempotencyKey,
        merchantRequestSnapshot,
        routeSnapshot,
        pricingSnapshot,
        expireAt,
        createdAt,
        paidAt,
        paymentToken,
        notifyUrl,
        returnUrl,
        customerReference,
        payoutDestinationRef,
        description,
        callbackStatus,
        callbackEventId,
        callbackAttemptCount,
        callbackLastNotifiedAt,
        callbackLastError);
  }
}
