package com.example.payments.trade.service.domain;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.UUID;

public record PaymentOrder(
    String orderId,
    String merchantId,
    String merchantOrderNo,
    String productCode,
    String paymentMethod,
    String country,
    String currency,
    BigDecimal amount,
    BigDecimal feeAmount,
    BigDecimal payerPayableAmount,
    BigDecimal netAmount,
    String feeBearer,
    OrderStatus status,
    String idempotencyKey,
    String routeSnapshot,
    String pricingSnapshot,
    Instant expireAt,
    Instant createdAt,
    Instant paidAt,
    String paymentToken,
    String notifyUrl,
    String returnUrl,
    String customerReference,
    String description,
    String callbackStatus,
    String callbackEventId,
    Integer callbackAttemptCount,
    Instant callbackLastNotifiedAt,
    String callbackLastError) {

  public static PaymentOrder create(
      String merchantId,
      String merchantOrderNo,
      String productCode,
      String paymentMethod,
      String country,
      String currency,
      BigDecimal amount,
      String idempotencyKey,
      Instant expireAt,
      String notifyUrl,
      String returnUrl,
      String customerReference,
      String description) {
    BigDecimal fee = amount.multiply(new BigDecimal("0.0200")).setScale(2);
    return new PaymentOrder(
        UUID.randomUUID().toString(),
        merchantId,
        merchantOrderNo,
        productCode,
        paymentMethod,
        country,
        currency,
        amount,
        fee,
        amount,
        amount.subtract(fee),
        "MERCHANT",
        OrderStatus.CREATED,
        idempotencyKey,
        "{\"route\":\"simulated-channel\",\"version\":1}",
        "{\"feeRate\":\"0.0200\",\"mode\":\"INCLUSIVE\",\"version\":1}",
        expireAt,
        Instant.now(),
        null,
        "simulated-token-" + UUID.randomUUID(),
        notifyUrl,
        returnUrl,
        customerReference,
        description,
        notifyUrl == null ? "NOT_CONFIGURED" : "READY",
        null,
        0,
        null,
        null);
  }

  public PaymentOrder withStatus(OrderStatus nextStatus, Instant paymentTime) {
    if (status.isTerminal() && status != nextStatus) {
      return this;
    }
    return new PaymentOrder(
        orderId,
        merchantId,
        merchantOrderNo,
        productCode,
        paymentMethod,
        country,
        currency,
        amount,
        feeAmount,
        payerPayableAmount,
        netAmount,
        feeBearer,
        nextStatus,
        idempotencyKey,
        routeSnapshot,
        pricingSnapshot,
        expireAt,
        createdAt,
        nextStatus == OrderStatus.SUCCESS ? paymentTime : paidAt,
        paymentToken,
        notifyUrl,
        returnUrl,
        customerReference,
        description,
        callbackStatus,
        callbackEventId,
        callbackAttemptCount,
        callbackLastNotifiedAt,
        callbackLastError);
  }

  public PaymentOrder withPricing(
      BigDecimal fee,
      BigDecimal payerPayable,
      BigDecimal net,
      String feeBearer,
      String routeSnapshot,
      String pricingSnapshot) {
    return new PaymentOrder(
        orderId,
        merchantId,
        merchantOrderNo,
        productCode,
        paymentMethod,
        country,
        currency,
        amount,
        fee,
        payerPayable,
        net,
        feeBearer,
        status,
        idempotencyKey,
        routeSnapshot,
        pricingSnapshot,
        expireAt,
        createdAt,
        paidAt,
        paymentToken,
        notifyUrl,
        returnUrl,
        customerReference,
        description,
        callbackStatus,
        callbackEventId,
        callbackAttemptCount,
        callbackLastNotifiedAt,
        callbackLastError);
  }
}
